-- | Checked manifests and read-only admission evidence.
module Eclips.Oracle.Admission
  ( HeraldAdmissionManifest,
    heraldAdmissionManifest,
    admissionManifestSystem,
    admissionManifestHeraldId,
    admissionManifestHeraldEpoch,
    HeraldJoinDigest,
    mkHeraldJoinDigest,
    heraldJoinDigestBytes,
    deriveHeraldJoinDigest,
    HeraldJoinMemberCut,
    heraldJoinMemberCut,
    joinMemberStampedPrefix,
    joinMemberInputPrefix,
    joinMemberStoreDigest,
    HeraldJoinSeal,
    heraldJoinSeal,
    joinSealAdmissionId,
    joinSealAttempt,
    joinSealTopologyCut,
    joinSealControlPrefix,
    joinSealMemberCuts,
    joinSealContributionDigest,
    joinSealRecipeDigest,
    joinSealDigest,
    HeraldJoinReadyReport,
    heraldJoinReadyReport,
    joinReadyAdmissionId,
    joinReadyAttempt,
    joinReadyReporter,
    joinReadySealDigest,
    joinReadyControlPrefix,
    joinReadyRecipeDigest,
    HeraldAdmissionPhase (..),
    HeraldAdmissionRecord,
    admissionRecordId,
    admissionRecordManifest,
    admissionRecordPredecessor,
    admissionRecordBeginIndex,
    admissionRecordChangedIndex,
    admissionRecordSemanticToken,
    admissionRecordAttempt,
    admissionRecordPhase,
    admissionRecordSeal,
    admissionRecordSealAcceptors,
    admissionRecordBaseReporters,
    admissionRecordBaseReports,
    admissionRecordNewcomerReport,
    HeraldAdmissionProblem (..),
    HeraldAdmissionCommand (..),
    encodeAdmissionCommand,
    decodeAdmissionCommand,
    encodeAdmissionRecord,
    decodeAdmissionRecord,
  ) where

import Eclips.Oracle.Internal.Admission
