-- | Checked live Oracle disappearance payloads and immutable result views.
module Eclips.Oracle.Disappearance
  ( DisappearanceInvalidationReason (..),
    DisappearanceAbortReason,
    authorizedDisappearanceAbortReason,
    CompleteDisappearanceEvidenceDigest,
    completeDisappearanceEvidenceDigest,
    completeDisappearanceEvidenceDigestBytes,
    DisappearanceCommandResult (..),
    DisappearanceRejection (..),
    DisappearanceProbeInvalidationView (..),
    DisappearanceProbeAbortReasonView (..),
    DisappearanceProbePhaseView (..),
    DisappearanceProbeView (..),
    ProjectedDisappearanceProbeHeader,
    admitProjectedDisappearanceProbeHeader,
    projectedDisappearanceProbeHeaderId,
    projectedDisappearanceProbeHeaderSubject,
    projectedDisappearanceProbeHeaderCoordinate,
    projectedDisappearanceProbeHeaderMembership,
  ) where

import Eclips.Oracle.Internal.Disappearance
  ( CompleteDisappearanceEvidenceDigest,
    DisappearanceAbortReason,
    DisappearanceCommandResult (..),
    DisappearanceInvalidationReason (..),
    DisappearanceProbeAbortReasonView (..),
    DisappearanceProbeInvalidationView (..),
    DisappearanceProbePhaseView (..),
    DisappearanceProbeView (..),
    DisappearanceRejection (..),
    ProjectedDisappearanceProbeHeader,
    admitProjectedDisappearanceProbeHeader,
    authorizedDisappearanceAbortReason,
    completeDisappearanceEvidenceDigest,
    completeDisappearanceEvidenceDigestBytes,
    projectedDisappearanceProbeHeaderCoordinate,
    projectedDisappearanceProbeHeaderId,
    projectedDisappearanceProbeHeaderMembership,
    projectedDisappearanceProbeHeaderSubject,
  )
