-- | Immutable semantic projection events and committed watch entries.
module Eclips.Oracle.Projection
  ( ProcessEpochRecord,
    ProcessOriginView (..),
    ProcessLifecycleView (..),
    processRecordProcessId,
    processRecordProcessEpoch,
    processRecordResidence,
    processRecordOrigin,
    processRecordLifecycle,
    OracleProjectionEvent,
    OracleProjectionEventView (..),
    oracleProjectionEventView,
    AppliedOracleEntry,
    AppliedOracleCommandEntry,
    appliedEntryCommand,
    appliedEntryConfiguration,
    appliedEntryReceiptRetirement,
    appliedEntryReceiptRetirementProgress,
    appliedEntryOracleProgress,
    appliedEntryControlIndex,
    appliedEntryRequestId,
    appliedEntryCommandDigest,
    appliedEntryReceipt,
    appliedEntryProjectionEvents,
    appliedEntryPostStateDigest,
  )
where

import Eclips.Oracle.Internal.Label
  ( AppliedOracleCommandEntry,
    AppliedOracleEntry,
    OracleProjectionEvent,
    OracleProjectionEventView (..),
    ProcessEpochRecord,
    ProcessLifecycleView (..),
    ProcessOriginView (..),
    appliedEntryCommand,
    appliedEntryCommandDigest,
    appliedEntryConfiguration,
    appliedEntryControlIndex,
    appliedEntryOracleProgress,
    appliedEntryPostStateDigest,
    appliedEntryProjectionEvents,
    appliedEntryReceipt,
    appliedEntryReceiptRetirement,
    appliedEntryReceiptRetirementProgress,
    appliedEntryRequestId,
    oracleProjectionEventView,
    processRecordLifecycle,
    processRecordOrigin,
    processRecordProcessEpoch,
    processRecordProcessId,
    processRecordResidence,
  )
