-- | Read-only queries over the opaque pure Oracle state.
module Eclips.Oracle.State
  ( oracleHeraldCatalogue,
    oracleHeraldAdmissions,
    oraclePendingHeraldAdmission,
    oracleHeraldAdmission,
    oracleDisappearanceProbe,
    oracleDisappearanceProbes,
    oracleRegularRetirementIndex,
    oracleControlledSubjectDisappeared,
    OracleState,
    OracleStateDigestMode (..),
    oracleStateDigestMode,
    oracleStateGenesis,
    oracleCheckpointBytes,
    decodeOracleCheckpoint,
    oracleRequestReceipts,
    oracleGreatestControlIndex,
    oracleStateDigest,
    oracleStateDiagnosticCardinalities,
    oracleStateDiagnosticSections,
    FailureProbeTerminalView (..),
    FailureProbeView (..),
    oracleCurrentMembership,
    oracleMembershipHistory,
    oracleCheckedMembershipHistory,
    oracleRetiredHeralds,
    oracleFailureProbe,
    oracleActiveFailureProbeFor,
    oracleRequestReceipt,
    oracleRequestRetirement,
    oracleReceiptRetirementFrontier,
    oracleReceiptRetirementProgress,
    oracleReceiptRetirementFrontiers,
    oracleReceiptRetirementProgresses,
    oracleProgresses,
    oracleLabelRetiredThrough,
    oracleLatestLabelDecision,
    oracleRequestCount,
    oracleLiveProcessResidence,
    oracleProcessRecord,
    oracleProcessRecords,
    oracleLabelRecord,
    oracleLabelRecords,
    oracleOpenDecisions,
    oracleObjectDecision,
    oracleOpenDecision,
    oracleWorkflowPhase,
    oracleLabelCollector,
    oracleTerminalOutcome,
    oracleCompletedWorkflowCount,
  )
where

import Eclips.Domain.Identity (HeraldEpoch, ProcessEpochId)
import Eclips.Oracle.Internal.Label
  ( FailureProbeTerminalView (..),
    FailureProbeView (..),
    OracleState,
    OracleStateDigestMode (..),
    ProcessLifecycleView (..),
    decodeOracleCheckpoint,
    oracleActiveFailureProbeFor,
    oracleCheckedMembershipHistory,
    oracleCheckpointBytes,
    oracleCompletedWorkflowCount,
    oracleControlledSubjectDisappeared,
    oracleCurrentMembership,
    oracleDisappearanceProbe,
    oracleDisappearanceProbes,
    oracleFailureProbe,
    oracleGreatestControlIndex,
    oracleHeraldAdmission,
    oracleHeraldAdmissions,
    oracleHeraldCatalogue,
    oracleLabelCollector,
    oracleLabelRecord,
    oracleLabelRecords,
    oracleLabelRetiredThrough,
    oracleLatestLabelDecision,
    oracleMembershipHistory,
    oracleObjectDecision,
    oracleOpenDecision,
    oracleOpenDecisions,
    oraclePendingHeraldAdmission,
    oracleProcessRecord,
    oracleProcessRecords,
    oracleProgresses,
    oracleReceiptRetirementFrontier,
    oracleReceiptRetirementFrontiers,
    oracleReceiptRetirementProgress,
    oracleReceiptRetirementProgresses,
    oracleRegularRetirementIndex,
    oracleRequestCount,
    oracleRequestReceipt,
    oracleRequestReceipts,
    oracleRequestRetirement,
    oracleRetiredHeralds,
    oracleStateDiagnosticCardinalities,
    oracleStateDiagnosticSections,
    oracleStateDigest,
    oracleStateDigestMode,
    oracleStateGenesis,
    oracleTerminalOutcome,
    oracleWorkflowPhase,
    processRecordLifecycle,
    processRecordResidence,
  )

oracleLiveProcessResidence ::
  ProcessEpochId -> OracleState -> Maybe HeraldEpoch
oracleLiveProcessResidence process state = do
  record <- oracleProcessRecord process state
  case processRecordLifecycle record of
    ProcessRecordLiveView -> Just (processRecordResidence record)
    ProcessRecordEndedView {} -> Nothing
