-- | Checked replica registration, committed voter configurations and retained
-- administration. Endpoint hints never confer membership or voting authority.
module Eclips.Oracle.Voter
  ( OracleReplicaEndpoint,
    oracleReplicaEndpoint,
    replicaEndpointHost,
    replicaEndpointPort,
    OracleReplicaContact,
    oracleReplicaContact,
    replicaContactOracle,
    replicaContactRaft,
    replicaContactDiscovery,
    OracleReplicaRegistration,
    replicaRegistrationNode,
    replicaRegistrationHost,
    replicaRegistrationContact,
    replicaRegistrationControlIndex,
    OracleVoterBindings,
    oracleVoterBindings,
    oracleVoterBindingList,
    VoterConfigurationId,
    voterConfigurationIdBytes,
    mkVoterConfigurationId,
    VoterConfiguration,
    voterConfigurationId,
    voterConfigurationNativeRef,
    VoterConfigurationView (..),
    voterConfigurationView,
    voterConfigurationBindings,
    voterConfigurationPredecessor,
    voterConfigurationControlIndex,
    voterConfigurationNative,
    VoterChangeId,
    voterChangeIdControlIndex,
    mkVoterChangeId,
    ExplicitVoterChangeReason (..),
    VoterChangeReason (..),
    VoterChangePhase (..),
    ConfigurationStage (..),
    VoterChange,
    voterChangeId,
    voterChangeExpectedConfiguration,
    voterChangeOldBindings,
    voterChangeNewBindings,
    voterChangeReason,
    voterChangePhase,
    voterChangeControlIndex,
    voterChangeLearners,
    VoterChangeProblem (..),
    VoterAdministrationResult (..),
    registerOracleReplicaCommand,
    beginVoterChangeCommand,
    cancelVoterChangeCommand,
    oracleCommandVoterChangeCancellation,
    oracleReplicaRegistrations,
    oracleReplicaReplicationTargets,
    oracleVoterConfiguration,
    oracleVoterConfigurations,
    oracleVoterChange,
    oraclePendingVoterChange,
    prepareOracleConfiguration,
    encodeReplicaRegistration,
    decodeReplicaRegistration,
    encodeVoterConfiguration,
    decodeVoterConfiguration,
    encodeVoterChange,
    decodeVoterChange,
  ) where

import Eclips.Oracle.Internal.Label
  ( beginVoterChangeCommand,
    cancelVoterChangeCommand,
    oracleCommandVoterChangeCancellation,
    oraclePendingVoterChange,
    oracleReplicaRegistrations,
    oracleReplicaReplicationTargets,
    oracleVoterChange,
    oracleVoterConfiguration,
    oracleVoterConfigurations,
    prepareOracleConfiguration,
    registerOracleReplicaCommand,
  )
import Eclips.Oracle.Internal.Voter
