-- | Safe pure vocabulary for a Herald's contiguous Oracle projection.
--
-- This interface belongs to the current internal prototype build. It grants
-- neither Oracle command-submission authority nor access to mutable projection
-- constructors.
module Eclips.Herald.OracleProjection
  ( State,
    View,
    initialState,
    initializeOracleVoters,
    oracleView,
    oracleViewSystemId,
    oracleViewControlIndex,
    oracleViewVoterConfiguration,
    oracleViewOracleReplicas,
    oracleViewVoterChanges,
    oracleViewVoterChange,
    oracleViewPendingVoterChange,
    oracleViewLocalHeraldEpoch,
    oracleViewCurrentHeraldMembership,
    oracleViewCurrentHeraldMembershipId,
    oracleViewHeraldMembershipHistory,
    oracleViewHeraldMembershipAt,
    oracleViewActiveHeralds,
    oracleViewActiveHeraldEpochs,
    oracleViewLocalHeraldIsCurrent,
    oracleViewInitialProjectionDigest,
    oracleViewIsActiveHerald,
    oracleViewProcessResidence,
    oracleViewProcessIsLive,
    oracleViewEndedProcess,
    oracleViewLabelWorkflowCompleted,
    oracleViewAuthorizesProcess,
    oracleViewStartedProcess,
    oracleViewSatisfiesPrerequisite,
    projectedProcessEpochs,
    projectedBootstraps,
    ProjectedStartedProcess,
    projectedStartedProcessBootstrap,
    projectedStartedProcessControlIndex,
    projectedStartedProcesses,
    ProjectedEndedProcess,
    projectedEndedProcessEpoch,
    projectedEndedProcessControlIndex,
    projectedEndedProcessReason,
    projectedEndedProcesses,
    TopologyControlCheckpointProblem (..),
    topologyControlCheckpointAt,
    appliedEntryEvidence,
    projectedOracleStateDigest,
    AppliedEntryClassification (..),
    classifyAppliedEntry,
    OracleProjectionFault (..),
    PreparedAppliedEntry,
    prepareAppliedEntry,
    preparedAppliedEntryClassification,
    commitAppliedEntry,
    OracleProjectionInvariant (..),
    OracleProjectionStateWitness,
    validateState,
    projectionWitnessControlIndex,
    projectionWitnessAppliedEntries,
    projectionWitnessStartedProcesses,
    projectionWitnessEndedProcesses,
    projectionWitnessPostStateDigest,
    OracleGenesisParityFault (..),
    OracleGenesisParityWitness,
    validateOracleGenesisParity,
    parityWitnessSystemId,
    parityWitnessActiveHeraldEpochs,
    parityWitnessInitialProjectionDigest,
  )
where

import Eclips.Herald.OracleProjection.State
