#!/usr/bin/env python3
"""Create ignored project-local wrappers for an already installed GHC RC.

Run from the repository root after the installation procedure in BUILDING.md.
This performs no downloads and refuses to overwrite an existing configuration.
"""

import argparse
import os
from pathlib import Path
import subprocess
import sys


VERSION = "9.14.1.20260728"
COMPILER_BIN = Path(".cabal/profile-0.2/f01/compiler-bin")
VERIFY_BIN = Path(".cabal/profile-0.2/p07/verify-bin")
INSTALL_BIN = Path(".cabal/profile-0.2/p07/ghc-rc/install/bin")


def fail(message):
    raise SystemExit(message)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cabal", required=True, type=Path,
                        help="path to the real cabal-install executable")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    if Path.cwd().resolve() != root or not (root / "cabal.project").is_file():
        fail("Run this script from the repository root.")

    cabal = args.cabal.resolve()
    if not cabal.is_file() or not os.access(cabal, os.X_OK):
        fail(f"Cabal executable is missing or not executable: {cabal}")
    if cabal == root / VERIFY_BIN / "cabal":
        fail("Pass the real cabal-install executable, not the generated wrapper.")
    for name in ("ghc", "ghc-pkg", "runghc", "haddock", "hsc2hs"):
        path = root / INSTALL_BIN / name
        if not path.is_file() or not os.access(path, os.X_OK):
            fail(f"Required RC tool is missing or not executable: {path}")
    for name, flag in (("ghc", "--numeric-version"), ("ghc-pkg", "--version")):
        version = subprocess.check_output(
            [root / INSTALL_BIN / name, flag], text=True).strip().split()[-1]
        if version != VERSION:
            fail(f"Expected {name} {VERSION}, found {version}; no files changed.")
    cabal_version = subprocess.check_output(
        [cabal, "--numeric-version"], text=True).strip()

    wrapper_prefix = '''#!/bin/sh
set -eu
project_root=$(CDPATH= cd -- "$(dirname -- "$0")/../../../.." && pwd)
'''
    files = {}
    for name in ("ghc", "haddock", "hsc2hs"):
        files[COMPILER_BIN / name] = wrapper_prefix + (
            f'exec "$project_root/{INSTALL_BIN}/{name}" "$@" '
            '+RTS -M2304m -RTS\n')
    files[COMPILER_BIN / "runghc"] = wrapper_prefix + (
        f'exec "$project_root/{INSTALL_BIN}/runghc" '
        '--ghc-arg=+RTS --ghc-arg=-M2304m --ghc-arg=-RTS "$@"\n')
    files[VERIFY_BIN / "cabal"] = wrapper_prefix + '''export CABAL_DIR="$project_root/.cabal"
exec "$project_root/.cabal/cabal-install" --store-dir="$project_root/.cabal/p07-rc-store" "$@"
'''
    files[Path(".cabal/profile-0.2/f01/env.sh")] = '''# Source from the repository root in every toolchain shell.
if [ ! -f "$PWD/cabal.project" ] || [ ! -x "$PWD/.cabal/profile-0.2/f01/compiler-bin/ghc" ]; then
    printf '%s\\n' 'Source the toolchain environment from the configured repository root.' >&2
    return 1
fi
if [ "$(uname -s)" = Darwin ] && [ -z "${DEVELOPER_DIR:-}" ]; then
    DEVELOPER_DIR=$(xcode-select -p) || return 1
    export DEVELOPER_DIR
fi
export PATH="$PWD/.cabal/profile-0.2/f01/compiler-bin:$PWD/.cabal/profile-0.2/p07/verify-bin:$PWD/.cabal/profile-0.2/p07/ghc-rc/install/bin:$PATH"
export TMPDIR="$PWD/.cabal/tmp"
export PYTHONDONTWRITEBYTECODE=1
export GHCRTS=-M768m
'''
    # CABAL_DIR in the wrapper supplies checkout-relative cache/log defaults.
    files[Path(".cabal/config")] = '''-- Generated by scripts/configure-local-toolchain.py.
repository hackage.haskell.org
  url: https://hackage.haskell.org/
  secure: True
jobs: 4
'''
    cabal_link = Path(".cabal/cabal-install")
    occupied = [str(path) for path in (*files, cabal_link)
                if os.path.lexists(root / path)]
    if occupied:
        fail("Existing local setup retained; refusing to overwrite: "
             + ", ".join(occupied))

    for path, content in files.items():
        target = root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        with target.open("x") as output:
            output.write(content)
        if path.parent in (COMPILER_BIN, VERIFY_BIN):
            target.chmod(0o755)
    (root / cabal_link).symlink_to(cabal)
    (root / ".cabal/tmp").mkdir(exist_ok=True)
    print(f"Configured GHC {VERSION} and cabal-install {cabal_version}.")
    print('Next: . "$PWD/.cabal/profile-0.2/f01/env.sh"')
    print('Then verify: ghc --numeric-version; cabal --config-file="$PWD/.cabal/config" path')


if __name__ == "__main__":
    try:
        main()
    except (OSError, subprocess.CalledProcessError) as error:
        sys.exit(str(error))
