-- | Application types, checked endpoints and session-owned operations.
--
-- Define one 'ApplicationSort' instance per payload type, compile its 'Sort',
-- and bind startup endpoints by name or create them through an 'Environment'.
-- Endpoint definitions are immutable. Identity checks happen at binding;
-- normal reads and writes use the resulting typed handle.
module Eclips.Application.Typed
  ( module Eclips.Application.Types.Typed,
    Herald,
    ConnectError (..),
    CallError (..),
    LifecycleCallError (..),
    CancelResult (..),
    module Eclips.Application.Connection,
    connect,
    disconnect,
    withHerald,
    startup,
    prepareChild,
    awaitChildReady,
    cancelChild,
    endProcess,
    TypedError (..),
    Nabla,
    Delta,
    Query,
    SomeQuery (..),
    Environment,
    Vertex,
    Edge,
    EdgeStrength (..),
    Sequencer,
    sequenceOn,
    sequenceOnVertex,
    sequenceOnEdge,
    EdgeReservation,
    Creation,
    Reservation,
    Object,
    bindNabla,
    bindDelta,
    nablaId,
    deltaId,
    nablaVertex,
    deltaVertex,
    vertexId,
    edgeId,
    reservationId,
    objectId,
    creationId,
    startupEnvironment,
    newEnvironment,
    environmentAccess,
    environmentHub,
    environmentEdges,
    environmentSelection,
    query,
    queryMany,
    newid,
    write,
    read,
    readObjects,
    localTake,
    wait,
    forward,
    label,
    reserve,
    cancelReservation,
    publishReserved,
    update,
    declareSort,
    sortVisible,
    createNabla,
    createDelta,
    createVertex,
    createEdge,
    reserveNabla,
    reserveDelta,
    reserveVertex,
    reserveEdgeFor,
    publishCreation,
    cancelCreation,
    discoverNablas,
    discoverDeltas,
    forwardEdge,
    labelVertex,
    labelEdge,
    reserveEdge,
    cancelReservedEdge,
  ) where

import Eclips.Application
  ( CallError (..),
    CancelResult (..),
    ConnectError (..),
    Herald,
    LifecycleCallError (..),
    awaitChildReady,
    cancelChild,
    connect,
    disconnect,
    endProcess,
    prepareChild,
    startup,
    withHerald,
  )
import Eclips.Application.Connection
import Eclips.Application.Typed.Internal
import Eclips.Application.Types.Typed
import Prelude hiding (read)
